"""Verify dedup_key unique constraint (intentional no-op)

Revision ID: a88a72ae9625
Revises: ff4b70c9fe6b
Create Date: 2026-05-04 11:57:56.917143

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "a88a72ae9625"
down_revision: str | Sequence[str] | None = "ff4b70c9fe6b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema.

    Intentional no-op. The dedup_key unique constraint is already created by
    revision ``842509edaa1f`` (table creation) and enforced as NOT NULL by
    revision ``ff4b70c9fe6b``. This revision exists only as a verification
    marker in the migration chain and keeps the production ``alembic_version``
    table consistent.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
