"""Ensure dedup_key unique constraint

Revision ID: a88a72ae9625
Revises: ff4b70c9fe6b
Create Date: 2026-05-04 11:57:56.917143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a88a72ae9625'
down_revision: Union[str, Sequence[str], None] = 'ff4b70c9fe6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
