"""Add unique index to dedup_key

Revision ID: ff4b70c9fe6b
Revises: 842509edaa1f
Create Date: 2026-05-03 18:36:23.324077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff4b70c9fe6b'
down_revision: Union[str, Sequence[str], None] = '842509edaa1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'dedup_key',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'dedup_key',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
